/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HospitalManagement.Pharmacy;

import java.awt.Desktop;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Inventory;
import model.PharmacyOrders;
import model.system;

/**
 *
 * @author arpid
 */
public class HMPOwnerOrders extends javax.swing.JPanel {

    /**
     * Creates new form HMPOwnerOrders
     */
    system s;
   
    public void getsum(){
        int q = 0;
        int p =0;
        int summ = 0;
        for(int i =0; i<tableorder.getRowCount();i++)
        {
            
            String quant = tableorder.getValueAt(i, 5).toString();
            String pric = tableorder.getValueAt(i, 4).toString();
            q = Integer.parseInt(quant);
            p = Integer.parseInt(pric);            
            summ = summ + (q*p);
            
        }
        
        bill.setText(Integer.toString(summ));
    }
    public void bill()
    {
         billarea.setText(billarea.getText()+"****************************************************\n");
         billarea.setText(billarea.getText()+"                       "+pharmacyname.getText()+"\n");
         billarea.setText(billarea.getText()+"****************************************************\n");
         billarea.setText(billarea.getText()+"Invoice Number:"+orderid.getText()+"\n"+"Date:"+date.getText()+"\n"+"Order To:"+centrename.getText()+"\n"+"\n");
         billarea.setText(billarea.getText()+"ITEMS              QUANTITY                PRICE\n"+"\n");
        
        for(int i =0; i<tableorder.getRowCount();i++)
        {
            String item = tableorder.getValueAt(i, 3).toString();
            String quant = tableorder.getValueAt(i, 5).toString();
            String price = tableorder.getValueAt(i, 4).toString();
            billarea.setText(billarea.getText()+item+"                           "+quant+"                    "+price+"\n");
            
        }
         billarea.setText(billarea.getText()+itemname.getText()+"                        "+ quantity.getText()+"                                "+price.getText()+
          "\n"+"\n"+"\n"+"\n"+"\n"+"\n"+"\n"+"\n"+
         "TOTAL:"+"                                                      "+bill.getText());
         billarea.setText(billarea.getText()+"\n"+"\n"+"\n"+"\n"+"\n"+"\n");
         billarea.setText(billarea.getText()+"****************************************************\n");
         billarea.setText(billarea.getText()+"                          Thank you"+"\n");
         billarea.setText(billarea.getText()+"****************************************************\n");
         
    }
    public HMPOwnerOrders(system s) {
        initComponents();
        this.s = s;
        populateTable();

         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pharmacyname = new javax.swing.JTextField();
        itemid = new javax.swing.JTextField();
        itemname = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pharmacyusername = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        itemtype = new javax.swing.JComboBox<>();
        bill = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        centrename = new javax.swing.JTextField();
        orderid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablephar = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        billarea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableorder = new javax.swing.JTable();
        generate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Pharmacy Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 324, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Item ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 423, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Quantity");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 361, -1, -1));
        jPanel2.add(pharmacyname, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 324, 80, -1));
        jPanel2.add(itemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 420, 80, -1));

        itemname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnameActionPerformed(evt);
            }
        });
        jPanel2.add(itemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 284, 80, -1));

        jButton2.setText("Select this Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 234, 118, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Pharmacy Username:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        jPanel2.add(pharmacyusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 284, 80, -1));
        jPanel2.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 358, 80, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Item Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 287, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Item Type");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 327, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Price");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 392, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Date");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 426, -1, -1));
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 423, 80, -1));
        jPanel2.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 389, 80, -1));

        itemtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Tablet", "Syrup", "Injection", "Other" }));
        jPanel2.add(itemtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 324, -1, -1));
        jPanel2.add(bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 476, 165, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Total Bill");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 479, 70, -1));
        jPanel2.add(centrename, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 392, 80, -1));

        orderid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderidActionPerformed(evt);
            }
        });
        jPanel2.add(orderid, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 358, 80, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setText("Order ID");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 70, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setText("Centre Name");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 395, -1, -1));

        tablephar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Pharmacy Name", "Pharmacy Id", "Item Id", "Item Name", "Item Price", "Quantity", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablephar);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 47, 475, 154));

        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 234, 113, -1));

        jButton1.setText("PRINT BILL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 710, 154, 31));

        billarea.setColumns(20);
        billarea.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        billarea.setRows(5);
        jScrollPane3.setViewportView(billarea);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 47, 490, 640));

        tableorder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Pharmacy Name", "Pharmacy Id", "Item Id", "Item Name", "Item Price", "Quantity", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableorder);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 525, 475, 220));

        generate.setText("GENERATE BILL");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });
        jPanel2.add(generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 710, 137, 31));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalManagement/Pharmacy/p pages.png"))); // NOI18N
        jLabel4.setDoubleBuffered(true);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void itemnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = tablephar.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tablephar.getModel();
        Inventory selectedep = (Inventory)model.getValueAt(row, 0);

        pharmacyusername.setText(String.valueOf(selectedep.getPharmacyusername()));
        pharmacyname.setText(String.valueOf(selectedep.getPharmacyname()));
        itemid.setText(String.valueOf(selectedep.getItemid()));
        itemname.setText(String.valueOf(selectedep.getItemname()));
        itemtype.setSelectedItem(String.valueOf(selectedep.getItemtype()));
        //                quantity.setText(String.valueOf(selectedep.getQuantity()));
        price.setText(String.valueOf(selectedep.getPrice()));
        //                date.setText(String.valueOf(selectedep.getDate()));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void orderidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderidActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        int sitem = Integer.parseInt(itemid.getText());
        int flag = 1;
        for (Inventory epp:s.getInventorydirectory().getInventory()){
            if (sitem == (epp.getItemid())){
                int s1 = epp.getQuantity();
                int s3 = Integer.parseInt(quantity.getText());
                epp.setQuantity(s1-s3);

            }

        }
        populateTable();
        String s1 = pharmacyusername.getText();
        String s2 = pharmacyname.getText();
        int s3 = Integer.parseInt(orderid.getText());
        String s4 = centrename.getText();
        int s5 = Integer.parseInt(itemid.getText());
        String s6 = itemname.getText();
        String s7 = (String)itemtype.getSelectedItem();
        int s8 = Integer.parseInt(quantity.getText());
        int s9 = Integer.parseInt(price.getText());
        String s10 = date.getText();
         if(s10.equals(""))
        {
           flag = 0;
           JOptionPane.showMessageDialog(this,"Please enter date");
           return;                     
        }
         if (s10.length()<10){
            flag = 0;
            JOptionPane.showMessageDialog(this,"Please enter correct date in format mm/dd/yyyy" );
            return;
        }
        
        StringBuffer sBuffer = new StringBuffer(s10);
        String mm;
        String dd;
        String yr;

        mm = sBuffer.substring(0,2);
        dd = sBuffer.substring(3,5);
        yr = sBuffer.substring(6,10);

        
        if(mm.matches("0[1-9]|1[0-2]") && dd.matches("0[1-9]|[12][0-9]|3[01]") && yr.matches("(19|20)\\d\\d"))
        {
          
        }
        else
        {
          flag = 0;  
         JOptionPane.showMessageDialog(this, "Please enter correct date in format mm/dd/yyyy");
         return;
        }
        
        if (flag==1){
        PharmacyOrders pp = s.getPharmacyordersdirectory().addNewPO();
        pp.setPharmacyusername(s1);
        pp.setPharmacyname(s2);
        pp.setCenterid(s3);
        pp.setCentrename(s4);
        pp.setItemid(s5);
        pp.setItemname(s6);
        pp.setItemtype(s7);
        pp.setQunatity(s8);
        pp.setPrice(s9);
        pp.setDate(s10);

        populateOrderTable();
        }

        //        pharmacyusername.setText("");
        //        pharmacyname.setText("Select");
        itemid.setText("");
        itemname.setText("");
        itemtype.setSelectedItem("Select");
        quantity.setText("");
        price.setText("");
        //        date.setText("");
        //        orderid.setText("");
        //        centrename.setText("");
        bill.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{

            billarea.print();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
        getsum();
        bill();
    }//GEN-LAST:event_generateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField bill;
    private javax.swing.JTextArea billarea;
    private javax.swing.JTextField centrename;
    private javax.swing.JTextField date;
    private javax.swing.JButton generate;
    private javax.swing.JTextField itemid;
    private javax.swing.JTextField itemname;
    private javax.swing.JComboBox<String> itemtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField orderid;
    private javax.swing.JTextField pharmacyname;
    public static javax.swing.JTextField pharmacyusername;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JTable tableorder;
    private javax.swing.JTable tablephar;
    // End of variables declaration//GEN-END:variables

private void populateTable() {
          DefaultTableModel model = (DefaultTableModel) tablephar.getModel();
          model.setRowCount(0);
        
        for (Inventory ep:s.getInventorydirectory().getInventory()){
//            if(pharmacyusername.equals(ep.getPharmacyusername())){
            
            Object[] row = new Object[7];
            row[0] = ep;
            row[1] = ep.getPharmacyusername();
            row[2] = ep.getItemid();
            row[3] = ep.getItemname();
            row[4] = ep.getPrice();
            row[5] = ep.getQuantity();
            row[6] = ep.getDate();      
            
            
            
            
            model.addRow(row);
            
}     
 
}

private void populateOrderTable() {
          DefaultTableModel model = (DefaultTableModel) tableorder.getModel();
          model.setRowCount(0);
        
        for (PharmacyOrders ep:s.getPharmacyordersdirectory().getPharmacyorders()){
            
            Object[] row = new Object[7];
            row[0] = ep;
            row[1] = ep.getPharmacyusername();
            row[2] = ep.getItemid();
            row[3] = ep.getItemname();
            row[4] = ep.getPrice();
            row[5] = ep.getQunatity();
            row[6] = ep.getDate();
            
            
            
            
            model.addRow(row);
}     
 
}


}
