/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BloodDonationManagement.Applicant;

import BloodDonationManagement.loginHR;
import Main.MainLogin;
import javax.swing.table.DefaultTableModel;
import model.Accept;
import model.Applicant;
import model.Reject;
import model.system;

/**
 *
 * @author arpid
 */
public class BDHiringApplicantPanel extends javax.swing.JFrame {

    /**
     * Creates new form BDHiringApplicantPanel
     */
    system s;
    public BDHiringApplicantPanel(system s) {
        initComponents();
        this.s = s;
//        this.setExtendedState(BDHiringApplicantPanel.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BDApplicantSplit = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        display = new javax.swing.JLabel();
        display1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setMinimumSize(new java.awt.Dimension(900, 800));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        display.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jPanel2.add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 54, 99, 48));

        display1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jPanel2.add(display1, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 54, 78, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodDonationManagement/Applicant/HP.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BDApplicantSplit.setRightComponent(jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("Job Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 205, 180, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton3.setText("Profile");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 164, 180, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton4.setText("Accepted Applications");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 246, 180, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton5.setText("Rejected Applications");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 287, 180, -1));

        home.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 328, 180, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton2.setText("Main Page");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 369, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodDonationManagement/Applicant/HP.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, -1));

        BDApplicantSplit.setLeftComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BDApplicantSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 1367, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BDApplicantSplit)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BDHiringApplicantJobSearch sapframe = new BDHiringApplicantJobSearch(s);
        BDApplicantSplit.setRightComponent(sapframe);
        BDHiringApplicantJobSearch.username1.setText(display1.getText());
         for (Applicant epp:s.getApplicantdirectory().getApplicant()){
            if(BDHiringApplicantJobSearch.username1.getText().equals(epp.getUsername())){
                BDHiringApplicantJobSearch.name1.setText(String.valueOf(epp.getName()));
                BDHiringApplicantJobSearch.age1.setText(String.valueOf(epp.getAge()));
                BDHiringApplicantJobSearch.gender1.setSelectedItem(String.valueOf(epp.getGender()));
                BDHiringApplicantJobSearch.id1.setText(String.valueOf(epp.getId()));
                BDHiringApplicantJobSearch.emailid1.setText(String.valueOf(epp.getEmailid()));                
                BDHiringApplicantJobSearch.contact1.setText(String.valueOf(epp.getContact()));                
                BDHiringApplicantJobSearch.qualification1.setText(String.valueOf(epp.getQualification()));
                
            }
         }
                
                
//                BDDonorSlotPanel.username.setText(String.valueOf(selectedep.getUsername()));
               
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        BDHiringApplicantProfile sapframe = new BDHiringApplicantProfile(s);
        BDApplicantSplit.setRightComponent(sapframe);
        
        BDHiringApplicantProfile.username.setText(display1.getText());
        for (Applicant epp:s.getApplicantdirectory().getApplicant()){
            if(BDHiringApplicantProfile.username.getText().equals(epp.getUsername())){
                BDHiringApplicantProfile.name.setText(String.valueOf(epp.getName()));
                BDHiringApplicantProfile.age.setText(String.valueOf(epp.getAge()));
                BDHiringApplicantProfile.gender.setSelectedItem(String.valueOf(epp.getGender()));
                BDHiringApplicantProfile.usertype.setSelectedItem(String.valueOf(epp.getUsertype()));
                BDHiringApplicantProfile.id.setText(String.valueOf(epp.getId()));
                BDHiringApplicantProfile.emailid.setText(String.valueOf(epp.getEmailid()));
                BDHiringApplicantProfile.bloodcentre.setText(String.valueOf(epp.getCentre()));
                BDHiringApplicantProfile.contact.setText(String.valueOf(epp.getContact()));
                BDHiringApplicantProfile.date.setText(String.valueOf(epp.getDate()));
                BDHiringApplicantProfile.qualification.setText(String.valueOf(epp.getQualification()));
                BDHiringApplicantProfile.username.setText(String.valueOf(epp.getUsername()));
                BDHiringApplicantProfile.password.setText(String.valueOf(epp.getPassword()));
                
//                BDDonorSlotPanel.username.setText(String.valueOf(selectedep.getUsername()));
               
               }}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        BDHiringAcceptedApplications sapframe = new BDHiringAcceptedApplications(s);
        BDApplicantSplit.setRightComponent(sapframe);   
        String user = display1.getText();
        BDHiringAcceptedApplications.username.setText(display1.getText());
        DefaultTableModel model = (DefaultTableModel) BDHiringAcceptedApplications.tableaccept.getModel();
        model.setRowCount(0);
        
        for (Accept ep:s.getAcceptdirectory().getAccept()){
                                                     
            if(user.equals(ep.getUsername()))
            {            
                Object[] row = new Object[4];
                row[0] = ep;
                row[1] = ep.getCentre();
                row[2] = ep.getId();
                row[3] = ep.getDate();                  
                       
                model.addRow(row);
            }
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        MainLogin sapframe = new MainLogin(s);
        sapframe.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_homeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        BDHiringRejectedApplications sapframe = new BDHiringRejectedApplications(s);
        BDApplicantSplit.setRightComponent(sapframe);   
        String user = display1.getText();
        BDHiringRejectedApplications.username.setText(display1.getText());
        DefaultTableModel model = (DefaultTableModel) BDHiringRejectedApplications.tableaccept.getModel();
        model.setRowCount(0);
        
        for (Reject ep:s.getRejectdirectory().getReject()){
                                                     
            if(user.equals(ep.getUsername()))
            {            
                Object[] row = new Object[4];
                row[0] = ep;
                row[1] = ep.getCentre();
                row[2] = ep.getId();
                row[3] = ep.getDate();                  
                       
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loginHR sapframe = new loginHR(s);
        sapframe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BDHiringApplicantPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BDHiringApplicantPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BDHiringApplicantPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BDHiringApplicantPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new BDHiringApplicantPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane BDApplicantSplit;
    public static javax.swing.JLabel display;
    public static javax.swing.JLabel display1;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
